config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: 'account'
    get 'users/profile', to: 'users/registrations#profile', as: 'profile'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    resources :reservations, only:[:new, :create, :show]
  end
  
  get 'reservations', to: 'reservations#index'
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></p>    
        </ul>
    <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>

app/views/shared/_roomform.html.erb
    <div class="container">
            <%= form_for @room do |f| %>
                <div class="form-group row">
                    <%= f.label :name, "ルーム名", class: "col-sm-2 col-form-label", for: "exampleName" %>
                    <div class="col-sm-10">
                        <%= f.text_field :name, class: "form-control", id: "exampleName", placeholder: "ルーム名を入力" %>
                    </div>
                </div>
                
                <div class="form-group row">
                    <%= f.label :introduction, "ルーム紹介", class: "col-sm-2 col-form-label", for: "exampleIntroduction" %>
                    <div class="col-sm-10">
                        <%= f.text_area :introduction, rows: 5, class: "form-control", id: "exampleIntroduction",placeholder: "ルームの説明を入力" %>
                    </div>
                </div>
                
                <div class="form-group row">
                    <%= f.label :fee, "料金", class: "col-sm-2 col-form-label", for: "exampleFee" %>
                    <div class="col-sm-10">
                        <%= f.number_field :fee, class: "form-control", id: "exampleFee", placeholder: "1日あたりの料金を入力" %>
                    </div>
                </div>
                
                <div class="form-group row">
                    <%= f.label :address, "住所", class: "col-sm-2 col-form-label", for: "exampleAddress" %>
                    <div class="col-sm-10">
                        <%= f.text_field :address, class: "form-control", id: "exampleAddress", placeholder: "住所を入力" %>
                    </div>
                </div>
            
                <div class="form-group row">
                    <%= f.label :image, "ルーム画像", class: "col-sm-2 col-form-label", for: "exampleImage" %>
                    <div class="col-sm-10">
                        <%= f.file_field :image, class: "form-control-file", id: "exampleImage" %>
                    </div>
                </div>
                
                <div class="form-group row">
                    <div class="col-sm-10">
                        <%= f.submit "登録", class: "btn btn-primary w-25" %>
                    </div>
                </div>
            <% end %>
    </div>

app/views/shared/_search_form.html.erb
<div class="d-flex">
  <%= form_with url: search_rooms_path, class: "form-inline", method: :get, local: true do |f| %>
    <%= f.text_field :area, class: "form-control mr-sm-2", placeholder: "エリア" %>
    <%= f.text_field :keyword, class: "form-control mr-sm-2", placeholder: "キーワード" %>
    <%= f.submit "検索", class: "btn btn-primary my-2 my-sm-0" %>
  <% end %>
</div>