config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: 'account'
    get 'users/profile', to: 'users/registrations#profile', as: 'profile'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    resources :reservations, only:[:new, :create, :show]
  end
  
  get 'reservations', to: 'reservations#index'
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many :reservations, dependent: :destroy
  
  # バリデーション
  validates :name, presence: true
  validates :fee, presence: true
  validates :introduction, length: { in: 0..50 }
  
  def self.search1(search) #両方が入力された場合
    if search
      Room.where('name LIKE(?) or address LIKE(?) or introduction LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    end
  end
  
  def self.search2(search) #エリアのみが入力された場合　住所のみを検索
    if search
      Room.where('address LIKE(?)', "%#{search}%")
    end
  end
  
  def self.search3(search) #キーワードのみが入力された場合　住所をのぞいて検索
    if search
      Room.where('name LIKE(?) or introduction LIKE(?)', "%#{search}%", "%#{search}%")
    end
  end
  
  def self.search4 
      Room.all
  end
  
  mount_uploader :image, ImageUploader
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
  end
  
  def search
    area = params[:area]
    keyword = params[:keyword]
    
    # 検索窓の入力状態によって処理の分岐
    if area.present? && keyword.present? #両方が入力された場合
      @rooms = Room.search1(area && keyword)
    elsif area.present? && keyword.blank? #エリアのみが入力された場合
      @rooms = Room.search2(area)
    elsif area.blank? && keyword.present? #キーワードのみが入力された場合
      @rooms = Room.search3(keyword)
    else
      @rooms = Room.search4() #入力が無い場合は全件表示
    end
  end
  
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "ルーム登録が完了しました。"
      redirect_to :root
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end
  
  def posts
    @user = User.find(current_user.id)
    @rooms = @user.rooms
  end
  
  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "ルーム名「#{@room.name}」の編集が完了しました。"
      redirect_to action: :posts
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "登録したルームを削除しました。"
    redirect_to action: :posts
  end
  
  private
  def room_params
    params.require(:room).permit(:name, :introduction, :fee, :address, :image).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= render "shared/roomform" %>

app/views/rooms/index.html.erb
<div class="card">
    <%= image_tag "/017kumakichi0327_TP_V.jpg", class: "card-img" %>
    <div class="card-img-overlay">
        <h5 class="card-title">旅に出かけよう！</h5>
        <%= render "shared/search_form" %>
    </div>
</div>

app/views/rooms/new.html.erb
<%= render "shared/error", obj: @room %>
<div class="container">
  <h4>ルーム登録</h4>
</div>
<%= render "shared/roomform" %>

app/views/rooms/posts.html.erb
<div class="container">
  <h4 class="pb-4">登録済みルーム一覧</h4>
    <table class="table">
      <thead>
        <tr align="center">
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>住所</th>
          <th>作成日</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr align="center">
            <td class="align-middle"><%= image_tag("#{room.image}") %></td>
            <td class="align-middle"><%= room.name %></td>
            <td class="align-middle"><%= room.introduction %></td>
            <td class="align-middle"><%= room.fee %></td>
            <td class="align-middle"><%= room.address %></td>
            <td class="align-middle"><%= room.created_at.to_s(:datetime_jp) %></td>
            <td class="align-middle">
              <%= link_to "編集", edit_room_path(room) %>
            </td>
            <td class="align-middle">
              <%= link_to "削除", room_path(room), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/rooms/search.html.erb
<div class="container">
  <h5><%= "検索結果#{@rooms.count}件" %></h5>
  
  <div class="album py-5 bg-light">
    <div class="cotainer">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <% @rooms.each do |room| %>
              <%= link_to room_path(room) do %>
                <%= image_tag("#{room.image}") %>
                <div class="card-body">
                  <h4 class="card-text"><span>ルーム名：</span><%= room.name %></h4>
                  <h6 class="card-text"><span>住所：</span><%= room.address %></h6>
                  <h6 class="card-text"><span>料金：¥</span>：</span><%= room.fee %></h6>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag("#{@room.image}") %>
      <div class="card">
        <div class="card-body">
          <%= link_to "/" do %>
            <p>投稿者アイコン</p>
            <%= image_tag("#{@room.user.image}") %>
          <% end %>
        </div>
        <div class="card-text">
          <h4>ルーム紹介</h4>
          <p class="room-show-profile-name"><span>ルーム名：</span><%=@room.name %></p>
          <p class="room-show-profile-address"><span>住所：</span><%=@room.address %></p>
          <p class="room-show-detail-introduction"><span>紹介：</span><%=@room.introduction %></p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="room-show-nav">
        <h5 class="price-icon"><span>¥</span><%= @room.fee %>/日</h5>
        <div class="room-show-date-select">
          <%= form_with url: new_room_reservation_path(@room.id), method: :get, local: true do |f| %>
          <div class="form-group row">
            <%= f.label :start_day, "開始日", class: "col-sm-3 col-form-label", for: "exampleSd" %>
            <div class="col-sm-10">
              <%= f.date_field :start_day, class: "form-control", id: "exampleSd" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :finish_day, "終了日", class: "col-sm-3 col-form-label", for: "exampleFd" %>
            <div class="col-sm-10">
              <%= f.date_field :finish_day, class: "form-control", id: "exampleFd" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :number, "人数", class: "col-sm-3 col-form-label", for: "exampleNumber" %>
            <div class="col-sm-10">
              <%= f.number_field :number, class: "form-control", id: "exampleFd"%>
            </div>
          </div>
            <%= f.hidden_field :room_id, :value => @room.id %>
          <div class="form-group row">
            <div class="col-sm-10">
            <%= f.submit "予約する", class: "btn btn-primary w-50" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>