config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  devise_scope :user do
    get 'users/account', to: 'users/registrations#account', as: 'account'
    get 'users/profile', to: 'users/registrations#profile', as: 'profile'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  
  resources :rooms do
    collection do
      get 'posts'
      get 'search'
    end
    resources :reservations, only:[:new, :create, :show]
  end
  
  get 'reservations', to: 'reservations#index'
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a href="/" class="navbar-brand">Sharing</a>
        <%= render "shared/search_form" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse dropleft" id="navbarSupportedContent">
            <% if user_signed_in? %>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    メニュー
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "ルーム登録", new_room_path, class: "dropdown-item" %>
                    <%= link_to "予約済みルーム一覧", reservations_path, class: "dropdown-item" %>
                    <%= link_to "登録済みルーム一覧", posts_rooms_path, class: "dropdown-item" %>
                    <%= link_to "設定", account_path, class: "dropdown-item" %>
                    <%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item", method: :delete %>
                  </div>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    メニュー
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %>
                    <%= link_to "新規登録", new_user_registration_path, class: "dropdown-item" %>
                  </div>
                </li>
              </ul>
            <% end %>
        </div>
      </nav>
    </header>
    <%= render "shared/flash" %>
    <main>
      <%= yield %>
    </main>
    <footer class="text-center">
        Copyright @yukishita
    </footer>
  </body>
</html>